version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - APP_ENV=production
      - APP_KEY=base64:...
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    volumes:
      - ./:/var/www
    networks:
      - laravel-network
    depends_on:
      - mysql

  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network

volumes:
  mysql-data:

networks:
  laravel-network: