name: Deploy

on:
  push:
    branches:
      - master

env:
  SERVER_HOST: 89.169.171.236
  SERVER_USER: user
  SERVER_PATH: /var/www/you-conf

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Настройка SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MY_KEY }}" > ~/.ssh/id_conf
          chmod 600 ~/.ssh/id_conf
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_conf
          ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

      # Исправление прав перед деплоем
      - name: Fix permissions on server
        run: |
          ssh -i ~/.ssh/id_conf -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "
            sudo chown -R ${{ env.SERVER_USER }}:${{ env.SERVER_USER }} ${{ env.SERVER_PATH}}
            sudo chmod -R 775 ${{ env.SERVER_PATH}}
          "

      # Deploy
      - name: Deploy to server
        run: |
          set -x
          # Копирование файлов с игнорированием прав
          rsync -avz --delete \
            --no-perms --no-owner --no-group \
            --exclude='node_modules' \
            --exclude='vendor' \
            --exclude='.env' \
            --exclude='storage' \
            -e "ssh -i ~/.ssh/id_conf -o StrictHostKeyChecking=no" \
            . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH}}

          # Выполнение команд обновления
          ssh -i ~/.ssh/id_conf -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "
            cd ${{ env.SERVER_PATH }} && \
            # Установка зависимостей
            if [ -f composer.json ]; then
              composer install --no-dev --optimize-autoloader
            fi && \
            if [ -f package.json ]; then
              yarn install && \
              yarn build
            fi && \
            # Фикс прав после деплоя
            sudo chown -R www-data:www-data ${{ env.SERVER_PATH}}/storage
            sudo chown -R www-data:www-data ${{ env.SERVER_PATH}}/bootstrap/cache
          "
