name: Deploy

on:
  push:
    branches:
      - master

env:
  SERVER_HOST: 89.169.171.236
  SERVER_USER: user
  SERVER_PATH: /var/www/you-conf

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Настройка SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MY_KEY }}" > ~/.ssh/id_conf
          chmod 600 ~/.ssh/id_conf
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_conf

      # Deploy
      - name: Deploy to server
        run: |
          set -x
          # Копирование файлов на сервер
          rsync --no-o --no-g --no-perms --compress --progress -e "ssh -i ~/.ssh/id_conf -o StrictHostKeyChecking=no -v" . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}

          # Выполнение команд на сервере
          ssh -i ~/.ssh/id_conf -o StrictHostKeyChecking=no -v ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "
            cd ${{ env.SERVER_PATH }} && \
            sudo apt-get remove -y cmdtest && \
            sudo apt-get remove -y yarn && \
            sudo apt-get remove --purge -y nodejs libnode72 && \  # Удаление конфликтующих пакетов
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && \
            echo 'deb https://dl.yarnpkg.com/debian/ stable main' | sudo tee /etc/apt/sources.list.d/yarn.list && \
            sudo apt-get update && \
            sudo apt-get install -y yarn && \
            # Установка Node.js
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && \
            sudo apt-get install -y nodejs && \
            # Удаление package-lock.json, если он существует
            rm -f package-lock.json && \
            composer install --no-dev --optimize-autoloader && \
            yarn install && \
            yarn build
          "
