name: Deploy

on:
  push:
    branches:
      - master

env:
  SERVER_HOST: 89.169.171.236
  SERVER_USER: user
  SERVER_PATH: /var/www/you-conf

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Настройка SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MY_KEY }}" > ~/.ssh/id_conf
          chmod 600 ~/.ssh/id_conf
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_conf

      # Deploy
      - name: Deploy to server
        run: |
          set -x
          rsync --archive --compress --progress -e "ssh -o StrictHostKeyChecking=no" . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}
          ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "cd ${SERVER_PATH} && composer install --no-dev --optimize-autoloader && yarn install && yarn build"
