name: Deploy

on:
  push:
    branches:
      - master

env:
  SERVER_HOST: 89.108.77.14
  SERVER_USER: user
  SERVER_PATH: /var/www/you-conf

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy
      - name: Deploy to server
        run: |
          rsync --archive --compress --progress . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}
          ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "cd ${SERVER_PATH} && composer install --no-dev --optimize-autoloader && yarn install && yarn build"
